name: Update DAGs and Deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-dags.yaml
      - dags/**

jobs:
  update-and-deploy:
    runs-on: centerm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.CENTERM_HOST }}
          SSH_PORT: ${{ secrets.CENTERM_PORT }}
          SSH_USER: ${{ secrets.CENTERM_USER }}
          SSH_KEY: ${{ secrets.CENTERM_KEY }}
          
      - run: ssh ${{ steps.ssh.outputs.SERVER }} bash -c "cd ${{ secrets.CENTERM_AIRFLOW_DIR }} && git pull --rebase"
