name: Update DAGs and Deploy

on:
  push:
    branches:
      - main
    paths:
      - dags/**

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Netbird
        run: |
          sudo apt-get update -qq && sudo apt-get install -y curl jq
          curl -fsSL https://pkgs.netbird.io/install.sh | sh
          
      - name: Connect to Netbird
        run: |
          sudo netbird up --setup-key ${{ secrets.NETBIRD_SETUP_KEY }}

      - name: Wait for Host to be Reachable
        run: |
          echo "Check Airflow host (max 3 mins)"
          end=$((SECONDS+180))
          while ! ping -c 1 ${{ secrets.CENTERM_HOST }} &> /dev/null; do
            if [ $SECONDS -ge $end ]; then
              echo "Timeout reached: host ${{ secrets.CENTERM_HOST }} still unreachable."
              exit 1
            fi
            echo "Waiting for host ${{ secrets.CENTERM_HOST }} to be reachable..."
            sleep 5
          done
          
      - name: SSH and Pull Latest Changes
        run: |
          sshpass -p "${{ secrets.CENTERM_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.CENTERM_USER }}@${{ secrets.CENTERM_HOST }} -p ${{ secrets.CENTERM_PORT }} \
          "cd ${{ secrets.CENTERM_AIRFLOW_DIR }} && git pull --rebase"
          
      - name: Disconnect from Netbird
        if: always()
        run: netbird down
