name: Update DAGs and Deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-dags.yaml
      - dags/**

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH and Pull Latest Changes
        run: |
          sshpass -p "${{ secrets.CENTERM_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.CENTERM_USER }}@${{ secrets.CENTERM_HOST }} -p ${{ secrets.CENTERM_PORT }} \
          "cd ${{ secrets.CENTERM_AIRFLOW_DIR }} && git pull --rebase"
